spring:
  sql:
    init:
      mode: always
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/movie_db
  application:
    name: Cinemax Movie
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
  main:
    banner-mode: off
logging:
  level:
    sql: info
server:
  port: 8080
