spring:
  ###### Email Properties ######
  #smtp mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenhaikiller@gmail.com
    password: ifhcfjmsfawbvkcs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      mode: embedded
      data-locations: classpath:/datasource/data.sql
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/movie_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Cinemax Movie
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    defer-datasource-initialization: true
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
logging:
  level:
    sql: info
server:
  port: 8080
application:
  security:
    jwt:
      email-verify:
        expiration: 300000
  jwt:
    token:
      Signerkey: ACus9GXSkhXg3iTEyjO1VTqmYRO7B7KNap0C70Alqf/87ZR9TS1YoCpEvonMzfrb
